name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  owasp-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Meu-Projeto'
          path: '.'            # Caminho do seu projeto
          format: 'HTML'       # ou 'ALL' para HTML, JSON, XML
          out: 'reports'       # Pasta onde os relatórios vão ficar
