name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  owasp-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Confirm Java setup
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version

      - name: Download Dependency-Check CLI
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.10/dependency-check-9.0.10-release.zip
          unzip -q dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "Devops-FIAP-RM358736" \
            --scan . \
            --out reports \
            --format HTML \
            --failOnCVSS 7
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: reports/
